### ISSUE TITLE
Skip managed frames

### ISSUE THREAD

**Issue by alobmaier** [goldshtn/msos#47]
Encountered a problem when using the mixed stack command on a mixed thread stack. Why the 
`else if (managedFrame > 0)` condition in [msos/MixedStack.cs](https://github.com/goldshtn/msos/blob/master/msos/MixedStack.cs) ?

In my scenario I stepped the stack with the built-in ClrMd ClrRuntime.Threads property and one time with msos. In msos I missed the last frame on top of the stack, due to the check, if there was a managed frame already. So if there was a frame without a native one associated with, the managed frame will get skipped.

**Comment by goldshtn** [comment]
Looks like a good catch. If we are at the top of the stack, `managedFrame == 0` and we might throw the frame away if there is no matching native frame. Would you like to fix this and submit a PR?

**Comment by alobmaier** [comment]
Sure, I am on it.
