### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by stej** [goldshtn/msos#62]
I've been searching how to fork a wiki and make a pull request, but with no luck..

So my proposed little changes. Rephrase according to your feeling of course (I'm not native speaker):
1) add 

> It's possible to comment msos commands. For single line comment use character `#`. For multi-line comment use `#` as well and end each line with `_`.

2) add this info to !hq section

> Also note that if you compare some field to `null`, cast the field to proper type. Compare these two commands and their outputs:
> ```
> 1> !hq tabular from s in ObjectsOfType("People") where s._name == null select s
> 1> !hq tabular from s in ObjectsOfType("People") where (string)s._name == null select s
> ```

**Comment by goldshtn** [comment]
Thanks for the contribution! I apologize for the delay. This has now been added to the wiki.
