### ISSUE TITLE
debuging  dump file throws the exception 

### ISSUE THREAD

**Issue by madhub** [goldshtn/msos#69]
Hi
I am trying to debug the dump file created from task manger and when I use the msos command  I get the following error message . I am trying to get the stack for all the threads.

```
D:\windows-backup\tools\msos-master\msos-master\msos\bin\x86\Release>msos.exe -z "C:\Users\bs_ma\AppData\Local\Temp\FeatureExploration (3).DMP"
An unexpected error occurred.
ClrDiagnosticsException: Unexpected relative addresses inconsistency between dump memory chunks 86 and 87.
```

Same dump when I open in visual studio I get the following  details.
------------
Dump File:	FeatureExploration (3).DMP : C:\Users\bs_ma\AppData\Local\Temp\FeatureExploration (3).DMP
Last Write Time:	2017-07-18 11:17:33 PM
Process Name:	FeatureExploration.exe : C:\dev\dotnet-dev\repos\DotNetDemos\FeatureExploration\bin\Release\FeatureExploration.exe
Process Architecture:	x86 (64-bit dump)
Exception Code:	not found
Exception Information:	
Heap Information:	Present

System Information
------------------
OS Version:	10.0.15063
CLR Version(s):	4.7.2101.1

Regards
Madhu

**Comment by goldshtn** [comment]
This happens because you have captured a dump of a 32-bit process using the 64-bit Task Manager on your system. This kind of dump is not supported by msos. You need to capture a 32-bit dump of the process, using either the 32-bit Task Manager (in `C:\Windows\SysWOW64\taskmgr.exe`) or some other utility capable of capturing 32-bit dumps correctly, such as Sysinternals Procdump.

**Comment by madhub** [comment]
I also tried using 64bit version of msos.exe it give some other error. I will post error shortly

**Comment by goldshtn** [comment]
Please read my reply. You will get an error when using either version of msos for this. You need to capture a 32-bit dump of the process using a 32-bit tool, such as 32-bit Task Manager or Procdump.
