### ISSUE TITLE
Can I use msos to get the thread dump for the threads

### ISSUE THREAD

**Issue by madhub** [goldshtn/msos#70]
Hi
I like the java tools which allows to dump thread stack for all the thread running in a java process. example [jstack -l  <pid>](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html) or [jcmd 37320 Thread.print](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr006.html).
Can I use the same using msos.exe .

Madhu

**Comment by Pavel-Durov** [comment]
what about  
`!StackTree           Display a stack tree of all the target's threads.` 

Example: 
`msos --pid 10580 -c  "!StackTree"`

> It displays a tree that aggregates all call stacks for all threads in the target, such that multiple threads that have the same call stack (or a part thereof) are displayed only once.

**Comment by goldshtn** [comment]
Indeed, `!StackTree` is an option. But generally speaking msos is a bit of an overkill for this. If you just want a stack dump of all the managed threads, I'd write a 15-line program that enumerates `ClrRuntime.Threads` and prints the `ClrThread.StackTrace` for each of them.
